In [2]:
import pandas as pd
%store -r pop_df

In [3]:
labour_force = pd.read_csv(r'C:\Users\HP\Desktop\Project Crime\Objectives\obj\Trend determiners\Labour_force.csv')
labour_force.head()

,FIPS_Code,State,Area_Name,Civilian_labor_force_2000,Employed_2000,Unemployed_2000,Unemployment_rate_2000,Civilian_labor_force_2001,Employed_2001,Unemployed_2001,...,Civilian_labor_force_2021,Employed_2021,Unemployed_2021,Unemployment_rate_2021,Civilian_labor_force_2022,Employed_2022,Unemployed_2022,Unemployment_rate_2022,Median_Household_Income_2021,Med_HH_Income_Percent_of_State_Total_2021
0,22073,Louisiana,Ouachita Parish,69592.0,66383.0,3209.0,4.6,70885.0,67122.0,3763.0,...,70104.0,66501.0,3603.0,5.1,70659.0,68082.0,2577.0,3.6,47737.0,91.6
1,22075,Louisiana,Plaquemines Parish,10981.0,10360.0,621.0,5.7,10995.0,10393.0,602.0,...,9587.0,9156.0,431.0,4.5,9805.0,9489.0,316.0,3.2,68765.0,132.0
2,22077,Louisiana,Pointe Coupee Parish,9711.0,9116.0,595.0,6.1,9530.0,8889.0,641.0,...,9662.0,9102.0,560.0,5.8,9863.0,9481.0,382.0,3.9,51988.0,99.8
3,22079,Louisiana,Rapides Parish,55496.0,52573.0,2923.0,5.3,55611.0,52359.0,3252.0,...,55554.0,53230.0,2324.0,4.2,56381.0,54566.0,1815.0,3.2,47316.0,90.8
4,22081,Louisiana,Red River Parish,3535.0,3296.0,239.0,6.8,3589.0,3307.0,282.0,...,3692.0,3527.0,165.0,4.5,3894.0,3766.0,128.0,3.3,40724.0,78.2

In [4]:
labour_force.drop(['FIPS_Code'],inplace = True, axis = 1)
labour_force.columns

Index(['State', 'Area_Name', 'Civilian_labor_force_2000', 'Employed_2000',
       'Unemployed_2000', 'Unemployment_rate_2000',
       'Civilian_labor_force_2001', 'Employed_2001', 'Unemployed_2001',
       'Unemployment_rate_2001', 'Civilian_labor_force_2002', 'Employed_2002',
       'Unemployed_2002', 'Unemployment_rate_2002',
       'Civilian_labor_force_2003', 'Employed_2003', 'Unemployed_2003',
       'Unemployment_rate_2003', 'Civilian_labor_force_2004', 'Employed_2004',
       'Unemployed_2004', 'Unemployment_rate_2004',
       'Civilian_labor_force_2005', 'Employed_2005', 'Unemployed_2005',
       'Unemployment_rate_2005', 'Civilian_labor_force_2006', 'Employed_2006',
       'Unemployed_2006', 'Unemployment_rate_2006',
       'Civilian_labor_force_2007', 'Employed_2007', 'Unemployed_2007',
       'Unemployment_rate_2007', 'Civilian_labor_force_2008', 'Employed_2008',
       'Unemployed_2008', 'Unemployment_rate_2008',
       'Civilian_labor_force_2009', 'Employed_2009', 'Unemployed_2009',
       'Unemployment_rate_2009', 'Civilian_labor_force_2010', 'Employed_2010',
       'Unemployed_2010', 'Unemployment_rate_2010',
       'Civilian_labor_force_2011', 'Employed_2011', 'Unemployed_2011',
       'Unemployment_rate_2011', 'Civilian_labor_force_2012', 'Employed_2012',
       'Unemployed_2012', 'Unemployment_rate_2012',
       'Civilian_labor_force_2013', 'Employed_2013', 'Unemployed_2013',
       'Unemployment_rate_2013', 'Civilian_labor_force_2014', 'Employed_2014',
       'Unemployed_2014', 'Unemployment_rate_2014',
       'Civilian_labor_force_2015', 'Employed_2015', 'Unemployed_2015',
       'Unemployment_rate_2015', 'Civilian_labor_force_2016', 'Employed_2016',
       'Unemployed_2016', 'Unemployment_rate_2016',
       'Civilian_labor_force_2017', 'Employed_2017', 'Unemployed_2017',
       'Unemployment_rate_2017', 'Civilian_labor_force_2018', 'Employed_2018',
       'Unemployed_2018', 'Unemployment_rate_2018',
       'Civilian_labor_force_2019', 'Employed_2019', 'Unemployed_2019',
       'Unemployment_rate_2019', 'Civilian_labor_force_2020', 'Employed_2020',
       'Unemployed_2020', 'Unemployment_rate_2020',
       'Civilian_labor_force_2021', 'Employed_2021', 'Unemployed_2021',
       'Unemployment_rate_2021', 'Civilian_labor_force_2022', 'Employed_2022',
       'Unemployed_2022', 'Unemployment_rate_2022',
       'Median_Household_Income_2021',
       'Med_HH_Income_Percent_of_State_Total_2021'],
      dtype='object')

In [5]:
phrase1= labour_force[['Civilian_labor_force_2000','Civilian_labor_force_2001','Civilian_labor_force_2002',
                                'Civilian_labor_force_2003','Civilian_labor_force_2004','Civilian_labor_force_2005',
                                'Civilian_labor_force_2006','Civilian_labor_force_2007','Civilian_labor_force_2008',
                                'Civilian_labor_force_2009','Civilian_labor_force_2010','Civilian_labor_force_2011',
                                'Civilian_labor_force_2012','Civilian_labor_force_2013','Civilian_labor_force_2014',
                                'Civilian_labor_force_2015','Civilian_labor_force_2016','Civilian_labor_force_2017',
                                'Civilian_labor_force_2018','Civilian_labor_force_2019','Civilian_labor_force_2020',
                                'Civilian_labor_force_2021',]]
phrase1.head()

,Civilian_labor_force_2000,Civilian_labor_force_2001,Civilian_labor_force_2002,Civilian_labor_force_2003,Civilian_labor_force_2004,Civilian_labor_force_2005,Civilian_labor_force_2006,Civilian_labor_force_2007,Civilian_labor_force_2008,Civilian_labor_force_2009,...,Civilian_labor_force_2012,Civilian_labor_force_2013,Civilian_labor_force_2014,Civilian_labor_force_2015,Civilian_labor_force_2016,Civilian_labor_force_2017,Civilian_labor_force_2018,Civilian_labor_force_2019,Civilian_labor_force_2020,Civilian_labor_force_2021
0,69592.0,70885.0,71533.0,71933.0,71308.0,72697.0,72383.0,71533.0,71150.0,71206.0,...,71006.0,70976.0,71668.0,71983.0,71640.0,70733.0,71010.0,70363.0,69470.0,70104.0
1,10981.0,10995.0,10955.0,11129.0,11504.0,NaN,NaN,8999.0,8395.0,7986.0,...,10179.0,10065.0,10195.0,10286.0,10197.0,10027.0,10075.0,10029.0,9542.0,9587.0
2,9711.0,9530.0,9376.0,9416.0,9460.0,9961.0,9558.0,9498.0,9565.0,9529.0,...,9921.0,9909.0,10061.0,10085.0,9972.0,10014.0,9930.0,9801.0,9459.0,9662.0
3,55496.0,55611.0,56083.0,56133.0,56237.0,59452.0,60069.0,59757.0,61659.0,60831.0,...,57491.0,57222.0,57784.0,57958.0,57346.0,56169.0,55557.0,55192.0,54760.0,55554.0
4,3535.0,3589.0,3647.0,3657.0,3542.0,3351.0,3268.0,3460.0,3466.0,3523.0,...,3963.0,3858.0,3974.0,3900.0,3813.0,3865.0,4057.0,3759.0,3588.0,3692.0

In [6]:
phrase2 = phrase1.sum(axis = 0).values
pop_labour_force = pd.DataFrame({'Year':pop_df['year'], 'Total_labour_force':phrase2.astype(int)})

In [7]:
pop_labour_force
%store pop_labour_force

Stored 'pop_labour_force' (DataFrame)

In [8]:
phrase3 = labour_force[[ 'State','Civilian_labor_force_2000','Employed_2000','Civilian_labor_force_2001','Employed_2001',
                        'Civilian_labor_force_2002','Employed_2002','Civilian_labor_force_2003','Employed_2003',
                        'Civilian_labor_force_2004','Employed_2004','Civilian_labor_force_2005','Employed_2005',
                        'Civilian_labor_force_2006','Employed_2006','Civilian_labor_force_2007','Employed_2007',
                        'Civilian_labor_force_2008','Employed_2008','Civilian_labor_force_2009','Employed_2009',
                        'Civilian_labor_force_2010','Employed_2010','Civilian_labor_force_2011','Employed_2011',
                        'Civilian_labor_force_2012','Employed_2012','Civilian_labor_force_2013','Employed_2013',
                        'Civilian_labor_force_2014','Employed_2014','Civilian_labor_force_2015','Employed_2015',
                        'Civilian_labor_force_2016','Employed_2016','Civilian_labor_force_2017','Employed_2017',
                        'Civilian_labor_force_2018','Employed_2018','Civilian_labor_force_2019','Employed_2019',
                        'Civilian_labor_force_2020','Employed_2020','Civilian_labor_force_2021','Employed_2021']]

In [9]:
phrase3 = phrase3.groupby('State').sum()
phrase3

,Civilian_labor_force_2000,Employed_2000,Civilian_labor_force_2001,Employed_2001,Civilian_labor_force_2002,Employed_2002,Civilian_labor_force_2003,Employed_2003,Civilian_labor_force_2004,Employed_2004,...,Civilian_labor_force_2017,Employed_2017,Civilian_labor_force_2018,Employed_2018,Civilian_labor_force_2019,Employed_2019,Civilian_labor_force_2020,Employed_2020,Civilian_labor_force_2021,Employed_2021
State,,,,,,,,,,,,,,,,,,,,,
Alabama,2147180.0,2047733.0,2128030.0,2017471.0,2112630.0,1987637.0,2128672.0,2001571.0,2138311.0,2018787.0,...,2203466.0,2103876.0,2240111.0,2152268.0,2272939.0,2200438.0,2269673.0,2124405.0,2259355.0,2183333.0
Alaska,319779.0,299590.0,321653.0,301422.0,327053.0,303560.0,332496.0,306966.0,337470.0,312396.0,...,360591.0,337107.0,355498.0,334069.0,353167.0,333362.0,347152.0,318300.0,353158.0,330525.0
Arizona,2510613.0,2410826.0,2593663.0,2470816.0,2683504.0,2518052.0,2728647.0,2571096.0,2788623.0,2649569.0,...,3240111.0,3079700.0,3325720.0,3166012.0,3430769.0,3265708.0,3471043.0,3199853.0,3530580.0,3352198.0
Arkansas,1260517.0,1207840.0,1261431.0,1201321.0,1276971.0,1209008.0,1282591.0,1208588.0,1302388.0,1229550.0,...,1348098.0,1297863.0,1343869.0,1294814.0,1354947.0,1307515.0,1346793.0,1263623.0,1339671.0,1285334.0
California,16837548.0,16011625.0,17096430.0,16160510.0,17246533.0,16081472.0,17271903.0,16081516.0,17374508.0,16293557.0,...,19185368.0,18258066.0,19289508.0,18469911.0,19413249.0,18617933.0,18971565.0,17047572.0,18973385.0,17586320.0
Colorado,2358379.0,2294111.0,2396018.0,2304556.0,2448907.0,2309643.0,2490398.0,2338430.0,2539396.0,2397591.0,...,2963796.0,2885982.0,3054351.0,2961427.0,3105583.0,3022828.0,3088992.0,2880226.0,3158146.0,2986238.0
Connecticut,1760697.0,1723592.0,1749199.0,1698596.0,1776065.0,1697788.0,1785735.0,1688380.0,1777520.0,1687124.0,...,1923713.0,1838835.0,1923874.0,1849371.0,1938640.0,1868768.0,1884101.0,1734480.0,1855340.0,1739036.0
Delaware,412956.0,398187.0,421564.0,406517.0,417207.0,399417.0,415889.0,397309.0,421092.0,402991.0,...,475213.0,453949.0,480370.0,462545.0,484658.0,467162.0,486497.0,449965.0,493930.0,466770.0
Florida,7917863.0,7620685.0,8048898.0,7692136.0,8050058.0,7651927.0,8123142.0,7760908.0,8347318.0,8033589.0,...,9972992.0,9544894.0,10118319.0,9749606.0,10284669.0,9950517.0,10113735.0,9292635.0,10353317.0,9872519.0
Georgia,4202699.0,4055365.0,4257916.0,4083538.0,4341633.0,4111634.0,4414292.0,4187010.0,4464789.0,4236308.0,...,5107907.0,4864825.0,5126943.0,4922498.0,5160528.0,4975977.0,5095711.0,4766740.0,5179135.0,4977575.0
Hawaii,605394.0,579736.0,607557.0,581379.0,601787.0,577616.0,603938.0,580353.0,611751.0,591594.0,...,695303.0,679865.0,692457.0,675848.0,686123.0,668773.0,664085.0,586179.0,669987.0,629626.0
Idaho,661075.0,630230.0,678281.0,643914.0,685659.0,647024.0,691704.0,653300.0,702882.0,668646.0,...,839780.0,812877.0,862436.0,837769.0,888504.0,862982.0,901898.0,852423.0,925407.0,893166.0
Illinois,6494442.0,6206065.0,6454099.0,6103098.0,6341899.0,5925994.0,6310532.0,5885145.0,6348738.0,5955750.0,...,6562302.0,6237936.0,6557425.0,6270843.0,6550309.0,6289519.0,6349826.0,5759011.0,6366437.0,5980447.0
Indiana,3125312.0,3030889.0,3143993.0,3010497.0,3161717.0,2997965.0,3178569.0,3011513.0,3165260.0,2993997.0,...,3333704.0,3217052.0,3392587.0,3276807.0,3404332.0,3291956.0,3346351.0,3102707.0,3355648.0,3225062.0
Iowa,1594404.0,1551440.0,1610638.0,1556927.0,1629057.0,1564185.0,1607935.0,1536510.0,1607440.0,1534643.0,...,1697510.0,1645663.0,1711823.0,1667823.0,1743161.0,1696692.0,1673598.0,1587344.0,1690382.0,1626177.0
Kansas,1402622.0,1349848.0,1398526.0,1338774.0,1419340.0,1347168.0,1441071.0,1361118.0,1458923.0,1378359.0,...,1488351.0,1434518.0,1493375.0,1443212.0,1504558.0,1455266.0,1503015.0,1415451.0,1500688.0,1451210.0
Kentucky,1957418.0,1876241.0,1953842.0,1852048.0,1944687.0,1832253.0,1965898.0,1844388.0,1969944.0,1861755.0,...,2053412.0,1955241.0,2052885.0,1966191.0,2068978.0,1983873.0,2017010.0,1886079.0,2027174.0,1937541.0
Louisiana,2026396.0,1921985.0,2027227.0,1913559.0,2013660.0,1892953.0,2024923.0,1897908.0,2030424.0,1914522.0,...,2108497.0,2000494.0,2109745.0,2007983.0,2105929.0,2008166.0,2064947.0,1887349.0,2073573.0,1958087.0
Maine,677466.0,654968.0,674964.0,649637.0,678540.0,648300.0,685155.0,649900.0,685968.0,654079.0,...,703873.0,680165.0,700855.0,678586.0,697789.0,677458.0,670595.0,636659.0,685168.0,653340.0
Maryland,2801396.0,2702435.0,2836286.0,2717446.0,2872366.0,2734978.0,2881029.0,2742967.0,2885111.0,2752186.0,...,3243898.0,3114581.0,3270636.0,3146485.0,3334368.0,3221318.0,3241085.0,3031031.0,3173291.0,3005067.0
Massachusetts,3340576.0,3246357.0,3386885.0,3258355.0,3436861.0,3257520.0,3419000.0,3223297.0,3400838.0,3226987.0,...,3724521.0,3582391.0,3818770.0,3686199.0,3841327.0,3725146.0,3750154.0,3399382.0,3742988.0,3535697.0
Michigan,5156711.0,4968890.0,5138853.0,4872127.0,5034731.0,4723289.0,5036121.0,4678905.0,5056153.0,4703966.0,...,4911256.0,4685855.0,4944803.0,4739083.0,4976013.0,4773456.0,4863016.0,4379125.0,4779560.0,4501565.0
Minnesota,2799120.0,2714003.0,2847963.0,2740874.0,2873013.0,2744745.0,2893378.0,2754859.0,2893486.0,2760750.0,...,3071011.0,2963832.0,3075098.0,2982665.0,3108690.0,3007378.0,3134166.0,2938018.0,3039326.0,2924152.0
Mississippi,1309884.0,1239845.0,1294742.0,1223542.0,1290798.0,1207800.0,1304585.0,1224556.0,1314989.0,1234122.0,...,1272692.0,1206101.0,1268048.0,1205346.0,1278600.0,1208100.0,1247035.0,1147393.0,1255719.0,1187101.0
Missouri,2971451.0,2870460.0,2987924.0,2853166.0,2981106.0,2823365.0,2983347.0,2814663.0,2995928.0,2819807.0,...,3053541.0,2939315.0,3048444.0,2949965.0,3074825.0,2975707.0,3037886.0,2851951.0,3050043.0,2925226.0
Montana,470076.0,447387.0,465356.0,443866.0,466414.0,445125.0,470511.0,448255.0,478221.0,456672.0,...,528443.0,506873.0,535147.0,515217.0,543742.0,524685.0,545342.0,513548.0,550557.0,531928.0
Nebraska,938857.0,912626.0,945376.0,915664.0,952938.0,917834.0,967048.0,928917.0,973638.0,935721.0,...,1023170.0,992745.0,1036414.0,1006284.0,1051560.0,1018711.0,1048391.0,1003442.0,1049590.0,1021331.0
Nevada,1070780.0,1026652.0,1113533.0,1055771.0,1134097.0,1069600.0,1150380.0,1089894.0,1178652.0,1126205.0,...,1444268.0,1372025.0,1494697.0,1429287.0,1546315.0,1482648.0,1506635.0,1302991.0,1499501.0,1395652.0
New Hampshire,685801.0,667603.0,692030.0,668573.0,700554.0,668985.0,708924.0,677383.0,715494.0,688271.0,...,758133.0,736919.0,770468.0,750284.0,780538.0,760517.0,764137.0,713147.0,756863.0,731120.0
New Jersey,4287640.0,4130824.0,4294366.0,4112095.0,4345276.0,4094390.0,4344387.0,4091466.0,4348047.0,4134064.0,...,4614956.0,4406152.0,4604790.0,4420714.0,4686268.0,4524295.0,4650328.0,4212388.0,4666113.0,4357219.0
New Mexico,846151.0,803667.0,855087.0,812554.0,866852.0,819276.0,880254.0,828393.0,890467.0,841004.0,...,948581.0,890989.0,944937.0,898362.0,956099.0,908705.0,931922.0,858352.0,943384.0,876733.0
New York,9140552.0,8727544.0,9126547.0,8680552.0,9294777.0,8718238.0,9283809.0,8689955.0,9359935.0,8816055.0,...,9838172.0,9382751.0,9826134.0,9424214.0,9853964.0,9474511.0,9580848.0,8645491.0,9557918.0,8886156.0
North Carolina,4127483.0,3972819.0,4191976.0,3956133.0,4209289.0,3917225.0,4285408.0,3997955.0,4287970.0,4036224.0,...,4865908.0,4646213.0,4911891.0,4715617.0,4993480.0,4801095.0,4839386.0,4491755.0,4954795.0,4712872.0
North Dakota,342768.0,332618.0,342526.0,332808.0,342474.0,330858.0,347107.0,335098.0,353659.0,341698.0,...,415769.0,404907.0,412073.0,402207.0,413857.0,404799.0,409804.0,389417.0,408907.0,396366.0
Ohio,5781450.0,5544343.0,5821163.0,5566420.0,5827498.0,5490094.0,5862999.0,5498961.0,5853726.0,5487221.0,...,5818986.0,5529483.0,5819990.0,5558126.0,5877460.0,5632578.0,5754705.0,5280932.0,5728776.0,5434819.0
Oklahoma,1655522.0,1605951.0,1672632.0,1611755.0,1685339.0,1607455.0,1686381.0,1595417.0,1690511.0,1610798.0,...,1826279.0,1752738.0,1831262.0,1771251.0,1840223.0,1782412.0,1841357.0,1725320.0,1860339.0,1785707.0
Oregon,1811842.0,1717626.0,1815082.0,1699365.0,1834256.0,1696897.0,1846328.0,1698482.0,1845412.0,1709562.0,...,2075687.0,1991506.0,2080050.0,1996490.0,2094783.0,2017199.0,2107365.0,1947570.0,2147616.0,2035430.0
Pennsylvania,6105746.0,5848149.0,6178910.0,5882822.0,6214546.0,5869306.0,6157934.0,5808101.0,6212835.0,5878612.0,...,6485256.0,6161914.0,6509784.0,6222012.0,6573614.0,6287803.0,6514576.0,5933188.0,6445367.0,6058976.0
Puerto Rico,1291997.0,1161034.0,1273414.0,1128704.0,1321376.0,1159460.0,1345789.0,1184591.0,1347049.0,1204536.0,...,1096546.0,977604.0,1081703.0,982173.0,1090862.0,1000368.0,0.0,0.0,1171948.0,1079108.0
Rhode Island,542518.0,520815.0,541663.0,517533.0,550244.0,522201.0,560786.0,529582.0,555681.0,526489.0,...,568146.0,542552.0,572664.0,549530.0,574347.0,554076.0,570186.0,517950.0,571697.0,540181.0
South Carolina,1965484.0,1892560.0,1941962.0,1839249.0,1954556.0,1828741.0,1999492.0,1855602.0,2043862.0,1891719.0,...,2261769.0,2166705.0,2282028.0,2205359.0,2324502.0,2259806.0,2335029.0,2195173.0,2353975.0,2261063.0
South Dakota,408499.0,398127.0,413499.0,401073.0,416806.0,403350.0,421530.0,406903.0,425956.0,410620.0,...,455339.0,441450.0,459206.0,446417.0,464339.0,451357.0,464511.0,444901.0,469588.0,457176.0
Tennessee,2849029.0,2738788.0,2857666.0,2728623.0,2898959.0,2750430.0,2904575.0,2744355.0,2897805.0,2742920.0,...,3197036.0,3077514.0,3257057.0,3143795.0,3335279.0,3223669.0,3303245.0,3056720.0,3323552.0,3174141.0
Texas,10388372.0,9932988.0,10539151.0,10014838.0,10742029.0,10061056.0,10910667.0,10176568.0,10998278.0,10336127.0,...,13474010.0,12888029.0,13714148.0,13178801.0,13921798.0,13429088.0,13955346.0,12883806.0,14311067.0,13503688.0
Utah,1142860.0,1104751.0,1162874.0,1112047.0,1179441.0,1112585.0,1197251.0,1130791.0,1231741.0,1170048.0,...,1554351.0,1505412.0,1584500.0,1538301.0,1618701.0,1577593.0,1647381.0,1567780.0,1687544.0,1641341.0
Vermont,334033.0,324664.0,338121.0,326970.0,343233.0,330074.0,346378.0,331240.0,347350.0,334548.0,...,355381.0,344698.0,355347.0,346556.0,353503.0,346015.0,339812.0,320543.0,335822.0,323352.0
Virginia,3606403.0,3524488.0,3681119.0,3559673.0,3739501.0,3576528.0,3772558.0,3609341.0,3814543.0,3658425.0,...,4352985.0,4193294.0,4359065.0,4228278.0,4414988.0,4292509.0,4342970.0,4062430.0,4331304.0,4162563.0
Washington,3087684.0,2929825.0,3085658.0,2900356.0,3101002.0,2881328.0,3136262.0,2910012.0,3189392.0,2988317.0,...,3727690.0,3554758.0,3814540.0,3645994.0,3933882.0,3766966.0,3936088.0,3603372.0,3898712.0,3695708.0
West Virginia,799088.0,754460.0,796592.0,753654.0,798714.0,747044.0,791846.0,739898.0,789535.0,743993.0,...,784740.0,743786.0,793418.0,752605.0,795306.0,755912.0,779923.0,715641.0,778756.0,739007.0
Wisconsin,2985644.0,2884739.0,3017690.0,2884306.0,3016764.0,2856237.0,3045311.0,2873960.0,3034620.0,2883573.0,...,3141758.0,3039351.0,3123896.0,3030654.0,3111736.0,3012830.0,3094725.0,2897425.0,3099768.0,2981067.0
Wyoming,265703.0,255727.0,268394.0,258171.0,269409.0,258574.0,272805.0,260993.0,274735.0,264188.0,...,293805.0,281164.0,292632.0,280754.0,293318.0,282431.0,293756.0,276496.0,289152.0,275747.0

In [10]:
#Plot a time-series gragh of 'phrase3' on Power BI